name: hiddify
description: Cross Platform Multi Protocol Proxy Frontend.
publish_to: "none"
version: 2.5.7+20507

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  # humanizer: ^2.2.0
  # intl: ^0.19.0
  humanizer:
    # git:
    #   url: https://github.com/alex-relov/humanizer
    #   ref: up-version
  # lucy_editor: ^1.0.5
  # re_highlight: ^0.0.3
  # json_editor_flutter: ^1.4.2

  slang:
  slang_flutter:
  fpdart: 
  freezed_annotation: 
  json_annotation: 
  hooks_riverpod: 
  flutter_hooks: 
  riverpod_annotation: 
  rxdart: 
  drift: 
  sqlite3_flutter_libs: 
  shared_preferences: 
  dio: 
  ffi: 
  path_provider:
  # mobile_scanner: ^5.1.1
  protocol_handler: 
  flutter_native_splash:
  share_plus: ^11.0.0
  window_manager: 
  tray_manager: 
  package_info_plus: ^8.3.0 
  url_launcher: 
  vclibs: 
  launch_at_startup: 
  sentry_flutter: ^9.3.0
  sentry_dart_plugin: ^3.1.0
  combine: 
    git:
      url: https://github.com/Maksimka101/combine.git
      ref: 49a02bc7b2d3636f7c3dba294371959f9f60a513
  path: 
  loggy:
  flutter_loggy: 
  meta: 
  dartx: 
  uuid: 
  tint: 
  accessibility_tools:
  neat_periodic_task: 
  watcher: 
  go_router: 
  flutter_animate: 
  flutter_svg: 
  gap: 
  percent_indicator: 
  sliver_tools: 
  flutter_adaptive_scaffold: 

  upgrader: any
  toastification: 
  version: 
  posix: 
  win32: 
  qr_flutter: 
  flutter_displaymode: 
  flutter_loggy_dio: 
  dio_smart_retry: 
  cupertino_http: 
  wolt_modal_sheet: 
  dart_mappable: 
  fluentui_system_icons: 
  http: 
  timezone_to_country:  ^3.0.0
  json_path: 
  # permission_handler: ^11.3.0 # is not compatible with windows
  #flutter_easy_permission: ^1.1.2
  # flutter_easy_permission:
  #   git:
  #     url: https://github.com/arcticfox1919/flutter_easy_permission.git
  #     ref: da0cf67a7c0a2d8ad257084956ce6d32a98f8ccc
    # ref: da0cf67a7c0a2d8ad257084956ce6d32a98f8ccc

  permission_handler: ^12.0.1
  in_app_review: 
  circle_flags:
    git: https://github.com/hiddify-com/flutter_circle_flags.git
  protobuf: 
  grpc: 
  dynamic_color: 
  flutter_typeahead: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
  build_runner:
  json_serializable:
  freezed:
  riverpod_generator:
  drift_dev: 
  ffigen:
  slang_build_runner: 
  flutter_gen_runner:
  go_router_builder: 
  dependency_validator:
  dart_mappable_builder:

dependency_overrides:
  # drift & package_info_plus are not compatible
  web:

flutter:
  uses-material-design: true
  assets:
    # - assets/core/geoip.db
    # - assets/core/geosite.db
    - assets/images/logo.svg
    - assets/images/tray_icon.ico
    - assets/images/tray_icon.png
    - assets/images/tray_icon_dark.ico
    - assets/images/tray_icon_dark.png
    - assets/images/tray_icon_connected.ico
    - assets/images/tray_icon_connected.png
    - assets/images/tray_icon_disconnected.ico
    - assets/images/tray_icon_disconnected.png
    - assets/images/connect_norouz.PNG
    - assets/images/disconnect_norouz.PNG

  fonts:
    - family: Shabnam
      fonts:
        - asset: assets/fonts/Shabnam.ttf
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/Roboto.ttf
    - family: Emoji
      fonts:
        - asset: assets/fonts/Emoji.ttf

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/source/ic_launcher_splash.png
  android_gravity: center
  android_12:
    color: "#ffffff"
    image: assets/images/source/ic_launcher_foreground.png

ffigen:
  name: "SingboxNativeLibrary"
  description: "Bindings to Singbox"
  output: "lib/gen/singbox_generated_bindings.dart"
  headers:
    entry-points:
      - "libcore/bin/libcore.h"

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  log_level: info
  ignore_missing: true
